name: Auto Merge PR
on:
 pull_request:
   types: [opened, ready_for_review]
jobs:
 auto-merge:
   runs-on: ubuntu-latest
   if: github.actor == 'sakshi-chauhan-maersk' 
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Setup Git
       run: |
         git config --global user.name "github-actions"
         git config --global user.email "actions@github.com"
     - name: Merge pull request
       run: |
         git fetch origin
         git checkout dev  
         git merge origin/update-doc  
         git push origin dev  
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}