name: Auto Merge PR

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - dev

jobs:
    automerge:
        if: github.actor == 'aniket-s-maersk' && github.event.pull_request.head.ref == 'update-doc'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Git
              run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Merge PR
              run: |
                    git checkout dev
                    git merge --no-ff ${{ github.event.pull_request.head.ref }}
                    git push origin dev