name: Auto Merge PRs

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize

jobs:
  automerge:
    if: github.actor == 'aniket-s-maersk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR base and head branches
        run: |
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"
          if [ "${{ github.event.pull_request.base.ref }}" = "dev" ] && [ "${{ github.event.pull_request.head.ref }}" = "update-doc" ]; then
            echo "Branches match, proceeding with auto-merge."
          else
            echo "Branches don't match, skipping auto-merge."
            exit 1
          fi

      - name: Merge the PR
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin dev
          git checkout dev
          git merge --no-ff "refs/pull/${{ github.event.pull_request.number }}/head" -m "Auto-merged PR from aniket"
          git push origin dev
